function Hd = Filter_CF_5_BW_8
%FILTER_CF_5_BW_8 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15.
% Generated on: 03-Jul-2024 14:21:31

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 340000000;  % Sampling Frequency

Fstop1 = 1000;        % First Stopband Frequency
Fpass1 = 1000000;     % First Passband Frequency
Fpass2 = 9000000;     % Second Passband Frequency
Fstop2 = 10000000;    % Second Stopband Frequency
Astop1 = 60;          % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 80;          % Second Stopband Attenuation (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
