function Hd = Filter_exp3_CF__3_5
%FILTER_EXP3_CF__3_5 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15.
% Generated on: 03-Jul-2024 20:10:40

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 340000000;  % Sampling Frequency

Fstop1 = 2000000;     % First Stopband Frequency
Fpass1 = 3000000;     % First Passband Frequency
Fpass2 = 4000000;     % Second Passband Frequency
Fstop2 = 5000000;     % Second Stopband Frequency
Astop1 = 60;          % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 80;          % Second Stopband Attenuation (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
